name: Daily AI Digest Bot

on:
  schedule:
    # Запускается ежедневно в 7:00 UTC (10:00 по Москве)
    - cron: '0 7 * * *'
  # Позволяет запускать вручную с сайта GitHub для тестирования
  workflow_dispatch:

jobs:
  build-and-send-digest:
    runs-on: ubuntu-latest
    # Устанавливаем таймаут для всей задачи на случай зависания
    timeout-minutes: 15

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # Шаг кэширования зависимостей
      - name: Cache pip dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip # Путь кэширования для pip
          # Ключ кэша генерируется на основе ОС, версии Python и хэша файла requirements.txt
          key: ${{ runner.os }}-python-${{ matrix.python-version }}-${{ hashFiles('**/requirements.txt') }}
          # Восстанавливать кэш, если ключ не совпадает полностью
          restore-keys: |
            ${{ runner.os }}-python-${{ matrix.python-version }}-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run digest agent
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          # Передаем секрет для администратора
          TELEGRAM_ADMIN_CHAT_ID: ${{ secrets.TELEGRAM_ADMIN_CHAT_ID }}
        run: python main.py