name: Daily AI Digest Bot

on:
  # Запуск каждый день в 7:00 по UTC (10:00 по МСК)
  schedule:
    - cron: '0 7 * * *'
  
  # Позволяет запускать вручную со страницы Actions на GitHub
  workflow_dispatch:

jobs:
  build-and-send-digest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run digest agent
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python main.py
